### ISSUE TITLE
Owned filter remains active after removing all students from collection

### ISSUE THREAD

**Issue by bLueriVerLHR** [SchaleDB/SchaleDB#45]
# The Bug

I was trying to remove all my students from collection, and I chose to filter them out by choosing to only show `Owned` students. 

However, after I removed all my students from collection, the mechanism which will try to hide collection choices from filter panel when there is no student in collection just activated. It means that I cannot simply cancel `Owned` choice to show student list all again. There did has way to recover by adding current student back to collection again, but it may sometimes be very confusing.

# Suggestion

I suggest removing hiding collection choices while there is no student in collection to avoid the situation.

Although it can fix this problem, I think u can come up with a more clever way to solve this 
problem.

Hope for ur reply.

**Comment by bLueriVerLHR** [comment]
I missed the icon which is a filter with a cross because it is not so conspicuous. 😂
Thx for ur reply. Very helpful.

**Comment by lonqie** [comment]
Keeping issue open as the bug is still present
