### ISSUE TITLE
Upcoming birthdays displays students without a valid birthday as 1/1

### ISSUE THREAD

**Issue by xiaofeiTM233** [SchaleDB/SchaleDB#59]
两位学生的档案中未记录生日但却显示1月1日过生日
![image](https://github.com/lonqie/SchaleDB/assets/55832499/4da8c378-1fcf-4683-ad61-0fdf24b5d22b)
食蜂操祈(Shokuhou_Misaki)、佐天涙子(Saten_Ruiko)
![image](https://github.com/lonqie/SchaleDB/assets/55832499/7558d147-ab46-4e49-9652-0e62b98160d0)
![image](https://github.com/lonqie/SchaleDB/assets/55832499/799e0585-164f-4d24-b400-8c677641f5a8)

**Comment by lonqie** [comment]
Keeping issue open for now, but this page will be reworked entirely as part of a large site upgrade/rework planned for this year
