### ISSUE TITLE
Incorrect buff stacking with T.S/Summon passive skills

### ISSUE THREAD

**Issue by phpnumber1** [SchaleDB/SchaleDB#65]
According to this video(https://www.bilibili.com/video/BV1T2421u7Ni ) , until 33s , he had cast Akari(NewYear), Chinatsu(Hot Spring) (both ex skill and ns), Mimoi(Swimsuit), Izuna, and in fact Izuna actually got 6 ATK SPEED buff. But according to your website, the ATK SPEED buff from Akari(NewYear) conflicts with the one from Izuna EX.

**Comment by lonqie** [comment]
7693ca5c7117c9e8f801869957de90297e9aeac9
