### ISSUE TITLE
Extra whitespace in jp/students.json

### ISSUE THREAD

**Issue by tolia512** [SchaleDB/SchaleDB#66]
Character ID: 10076
"PersonalName": " コトリ",
Character ID: 10079
"PersonalName": " 美琴",

Character ID: 20018
"Weapon": {
    "Name": " RABBIT-224式拳銃",

**Comment by lonqie** [comment]
I'm closing this issue for now as it's not a website bug, and the additional whitespace present in the data doesn't affect the display on Schale DB as it is ignored in web pages.
If this does become an issue in the future it will be addressed but for now it is not a priority.
