### ISSUE TITLE
Web pages cannot be opened in certain languages

### ISSUE THREAD

**Issue by systemannounce** [SchaleDB/SchaleDB#67]
If you adjust the language to ภาษาไทย, Traditional Chinese, Simplified Chinese, then you will not be able to open the web page, it seems because the name of the event has not been successfully replaced, but the English lacks translation, and Japanese display can be used normally. Other languages But no.
![image](https://github.com/SchaleDB/SchaleDB/assets/55303494/498ee665-a100-416e-9bbd-51e1e65f1313)
![image](https://github.com/SchaleDB/SchaleDB/assets/55303494/e23ed6bd-b39e-4263-9be4-4a1a76515300)

**Comment by lonqie** [comment]
6f8c72348877d6bf2faa30fb83b5e0cc4b4bb6c9
