### ISSUE TITLE
camp kotama NS channel issue

### ISSUE THREAD

**Issue by NintendoAris** [SchaleDB/SchaleDB#73]
calculator considers kazusa's NS and camp kotama's NS as not stackable, but they are stackable.

**Comment by lonqie** [comment]
Fixed in v271 23a73fe68e4c9950dbfb49e3bdb93046550cebf1

These types of skills will apply the correct channel depending on if it's applied to self or a different ally.
Issue also affected Hibiki (Cheer Squad) basic skill.
