### ISSUE TITLE
student simulation increase damage

### ISSUE THREAD

**Issue by ivealive** [SchaleDB/SchaleDB#79]
Problems that cannot reflect the increase in the amount of general tactical tests taken in student detail

**Comment by lonqie** [comment]
Sorry but I cannot understand the question or issue at all.
Could you please rephrase or elaborate, or provide a screenshot to help me understand this?

**Comment by ivealive** [comment]
<img width="448" alt="11111" src="https://github.com/SchaleDB/SchaleDB/assets/172942144/871aec2f-5eac-4b6b-9c51-3e85e0f3417c">

**Comment by ivealive** [comment]
<img width="990" alt="11111" src="https://github.com/SchaleDB/SchaleDB/assets/172942144/7e0d14f7-d222-41a9-b94e-f883df9f362b">
sorry problem has been solved.

**Comment by lonqie** [comment]
You haven't set that up correctly if you're trying to calculate damage in Joint firing drill with the full increase from the Scarecrow.
By default those enemies have 90% reduction, or `DamagedRatio = 19000`. Each stack reduces this by 5 percentage pts/500 (so a 50% increase in damage relative to the unmodified value per stack).
For 10 stacks you would want to add a flat -5000 to get a final dmg reduction of 40%
