### ISSUE TITLE
Wrong text in Hieronymus's Enhanced Skill "Holy Light (Relic)"

### ISSUE THREAD

**Issue by clufox37** [SchaleDB/SchaleDB#81]
![캡처_2024_08_01_21_33_58_467](https://github.com/user-attachments/assets/1d84f8eb-ea96-4fc8-8d88-13cc83154386)
![캡처_2024_08_01_22_02_15_787](https://github.com/user-attachments/assets/70c77f2a-019e-4223-8942-3e1328c9a295)
![캡처_2024_08_01_22_05_11_533](https://github.com/user-attachments/assets/1b8b5b82-88f6-4291-bec9-8fd9e96ed8cb)
![캡처_2024_08_01_22_06_05_268](https://github.com/user-attachments/assets/33afc564-aff7-4262-bcd3-394e8e183f54)

![캡처_2024_08_01_21_57_59_765](https://github.com/user-attachments/assets/42db12d4-56d7-4cd4-a92a-9a80c03caa43)

"it loses 95% of its HP" is not included in the official skill description, and it is totally wrong data.
The green relic takes 250% damage of its HP, at INSANE~TORMENT difficulty.

![캡처_2024_08_01_22_07_05_117](https://github.com/user-attachments/assets/e0208f67-3766-43ed-86a3-d422c99c38a1)
![캡처_2024_08_01_22_20_48_795](https://github.com/user-attachments/assets/d4f84ebf-6a93-4e28-a8e9-d03f707e75fb)

Japanese and Thai descriptions are correct. But other language descriptions(en, kr, cn) need to be corrected.

**Comment by lonqie** [comment]
Very often extra information is added to skill text that is not present in the in-game tooltips.

In this case the description is correct for the difficulties Normal through Extreme, the relic is damaged by an amount equal to 95% of its Max HP:
![image](https://github.com/user-attachments/assets/d26efcf5-ae07-495f-b0bc-72669ebce16f)
This example is from Normal difficulty, where the green relic has 6,002 Max HP

In Insane and Torment, as you say, this damage is increased to 250% and the text on Schale DB was not updated to reflect this change
